### ISSUE TITLE
Installing Contiv on a newly added worker node fails on a swarm cluster

### ISSUE THREAD

**Issue by sisudhir** [contiv/install#247]
We have a 10 node swarm cluster in which the first three nodes are contiv masters and the rest of them are contiv workers. Added a new worker node into this cluster - swarm join succeeds  without any issue where as installing contiv on the added node fails.

1) We used cfg.yml to have only new node as on a non-master role. -
TASK [contiv_network : install v2plugin on master nodes] ***********************
fatal: [node1]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.61 control_url=10.65.122.61:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.500553", "end": "2017-09-12 15:54:32.715870", "failed": true, "rc": 1, "start": "2017-09-12 15:54:24.215317", "stderr": "Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists", "stderr_lines": ["Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists"], "stdout": "", "stdout_lines": []}
fatal: [node2]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.63 control_url=10.65.122.63:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.496039", "end": "2017-09-12 15:54:32.718202", "failed": true, "rc": 1, "start": "2017-09-12 15:54:24.222163", "stderr": "Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists", "stderr_lines": ["Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists"], "stdout": "", "stdout_lines": []}
fatal: [node3]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.62 control_url=10.65.122.62:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.490665", "end": "2017-09-12 15:54:32.728627", "failed": true, "rc": 1, "start": "2017-09-12 15:54:24.237962", "stderr": "Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists", "stderr_lines": ["Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/ansible/install_plays.retry

PLAY RECAP *********************************************************************
node1                      : ok=14   changed=5    unreachable=0    failed=1
node10                     : ok=8    changed=3    unreachable=0    failed=0
node11                     : ok=8    changed=3    unreachable=0    failed=0
node2                      : ok=14   changed=5    unreachable=0    failed=1
node3                      : ok=14   changed=5    unreachable=0    failed=1
node4                      : ok=8    changed=3    unreachable=0    failed=0
node5                      : ok=8    changed=7    unreachable=0    failed=0
node6                      : ok=8    changed=3    unreachable=0    failed=0
node7                      : ok=8    changed=3    unreachable=0    failed=0
node8                      : ok=8    changed=3    unreachable=0    failed=0
node9                      : ok=8    changed=3    unreachable=0    failed=0

2) Then we tried to have all the node entries including the new one, in the cfg.yml, assuming already installed nodes will be skipped for contiv install, but this also failed. 

We need to have tested way to install Contiv on newly added node to the existing swarm cluster.

**Comment by rchirakk** [comment]
@neelimamukiri ^^
@sisudhir  is the error log for adding node-10 ?
I see ansible failure for node1,node2,node3

**Comment by rhim** [comment]
Cristian can help out on this. @rchirakk please ask any clarifying questions as appropriate. Thanks.

**Comment by sisudhir** [comment]
@rchirakk - We have followed the same steps as you have suggested above. Here are the logs -

1) Installer play recap -

node11                     : ok=8    changed=4    unreachable=0    failed=0

2) Node11 -> DEE-Wrk-5 has this `docker plugin ls` status -

[root@DEE-Wrk-5 ~]# docker plugin ls
ID                  NAME                DESCRIPTION         ENABLED

3) `etcdctl cluster-health` ran on newly added node does show correct health-status -

[root@DEE-Wrk-5 ~]# etcdctl cluster-health
member 90664c9dc2965304 is healthy: got healthy result from http://10.65.122.63:2379
member 9e88c8024b6e7f1f is healthy: got healthy result from http://10.65.122.62:2379
member e72916cdaaf6d375 is healthy: got healthy result from http://10.65.122.61:2379
cluster is healthy

4) Newly added node doesn't have `netctl` installed even though installer play shows `0` failed tasks - 

[root@DEE-Wrk-5 ~]# which netctl
/usr/bin/which: no netctl in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

5) It seems playbook attempted installation of v2plugin on manager nodes, instead of skipping the tasks, and eventually playbook terminated there itself, w/o proceeding further -

TASK [contiv_network : install v2plugin on master nodes] ***********************
fatal: [node3]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.62 control_url=10.65.122.62:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.473737", "end": "2017-09-13 11:01:27.104818", "failed": true, "rc": 1, "start": "2017-09-13 11:01:18.631081", "stderr": "Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists", "stderr_lines": ["Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists"], "stdout": "", "stdout_lines": []}
fatal: [node1]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.61 control_url=10.65.122.61:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.457114", "end": "2017-09-13 11:01:27.107271", "failed": true, "rc": 1, "start": "2017-09-13 11:01:18.650157", "stderr": "Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists", "stderr_lines": ["Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists"], "stdout": "", "stdout_lines": []}
fatal: [node2]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.63 control_url=10.65.122.63:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.526772", "end": "2017-09-13 11:01:27.150624", "failed": true, "rc": 1, "start": "2017-09-13 11:01:18.623852", "stderr": "Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists", "stderr_lines": ["Error response from daemon: plugin \"contiv/v2plugin:1.1.1\" already exists"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/ansible/install_plays.retry

Here are the logs from all 3 manager nodes, cfg.yml and env.json files used for adding a node to existing cluster.

[DEE-Ctrl-1.tar.gz](https://github.com/contiv/install/files/1298471/DEE-Ctrl-1.tar.gz)
[DEE-Ctrl-2.tar.gz](https://github.com/contiv/install/files/1298470/DEE-Ctrl-2.tar.gz)
[DEE-Ctrl-3.tar.gz](https://github.com/contiv/install/files/1298472/DEE-Ctrl-3.tar.gz)

[cfg.txt](https://github.com/contiv/install/files/1298476/cfg.txt)
[env.txt](https://github.com/contiv/install/files/1298480/env.txt)

**Comment by rhim** [comment]
Looks like our ansible should have a check step. Blindly reinstalling will fail.

-Himanshu

On Sep 12, 2017, at 11:55 PM, sisudhir <notifications@github.com<mailto:notifications@github.com>> wrote:


@rchirakk<https://github.com/rchirakk> - We have followed the same steps as you have suggested above. Here are the logs -

  1.  Installer play recap -

node11 : ok=8 changed=4 unreachable=0 failed=0

  1.  Node11 -> DEE-Wrk-5 has this docker plugin ls status -

[root@DEE-Wrk-5 ~]# docker plugin ls
ID NAME DESCRIPTION ENABLED

  1.  etcdctl cluster-health ran on newly added node does show correct health-status -

[root@DEE-Wrk-5 ~]# etcdctl cluster-health
member 90664c9dc2965304 is healthy: got healthy result from http://10.65.122.63:2379
member 9e88c8024b6e7f1f is healthy: got healthy result from http://10.65.122.62:2379
member e72916cdaaf6d375 is healthy: got healthy result from http://10.65.122.61:2379
cluster is healthy

  1.  Newly added node doesn't have netctl installed even though installer play shows 0 failed tasks -

[root@DEE-Wrk-5 ~]# which netctl
/usr/bin/which: no netctl in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

  1.  It seems playbook attempted installation of v2plugin on manager nodes, instead of skipping the tasks, and eventually playbook terminated there itself, w/o proceeding further -

TASK [contiv_network : install v2plugin on master nodes] ***********************
fatal: [node3]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.62 control_url=10.65.122.62:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.473737", "end": "2017-09-13 11:01:27.104818", "failed": true, "rc": 1, "start": "2017-09-13 11:01:18.631081", "stderr": "Error response from daemon: plugin "contiv/v2plugin:1.1.1" already exists", "stderr_lines": ["Error response from daemon: plugin "contiv/v2plugin:1.1.1" already exists"], "stdout": "", "stdout_lines": []}
fatal: [node1]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.61 control_url=10.65.122.61:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.457114", "end": "2017-09-13 11:01:27.107271", "failed": true, "rc": 1, "start": "2017-09-13 11:01:18.650157", "stderr": "Error response from daemon: plugin "contiv/v2plugin:1.1.1" already exists", "stderr_lines": ["Error response from daemon: plugin "contiv/v2plugin:1.1.1" already exists"], "stdout": "", "stdout_lines": []}
fatal: [node2]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.1.1 ctrl_ip=10.65.122.63 control_url=10.65.122.63:9999 vxlan_port=8472 iflist=eno2 plugin_name=contiv/v2plugin:1.1.1 cluster_store=etcd://localhost:2379 plugin_role=master", "delta": "0:00:08.526772", "end": "2017-09-13 11:01:27.150624", "failed": true, "rc": 1, "start": "2017-09-13 11:01:18.623852", "stderr": "Error response from daemon: plugin "contiv/v2plugin:1.1.1" already exists", "stderr_lines": ["Error response from daemon: plugin "contiv/v2plugin:1.1.1" already exists"], "stdout": "", "stdout_lines": []}
to retry, use: --limit @/ansible/install_plays.retry

Here are the logs from all 3 manager nodes, cfg.yml and env.json files used for adding a node to existing cluster.

DEE-Ctrl-1.tar.gz<https://github.com/contiv/install/files/1298471/DEE-Ctrl-1.tar.gz>
DEE-Ctrl-2.tar.gz<https://github.com/contiv/install/files/1298470/DEE-Ctrl-2.tar.gz>
DEE-Ctrl-3.tar.gz<https://github.com/contiv/install/files/1298472/DEE-Ctrl-3.tar.gz>

cfg.txt<https://github.com/contiv/install/files/1298476/cfg.txt>
env.txt<https://github.com/contiv/install/files/1298480/env.txt>

-

**Comment by unclejack** [comment]
I'm working on this.

**Comment by rhim** [comment]
@dojacobs also has a repro in our lab

**Comment by dojacobs** [comment]
What I did was use the QA-Jenkins Netplugin-End-To-End job I've written to test Contiv.

First, I ran it with the following parameters:
Platform = vcenter
Orchestrator = docker-swarm
DockerVersion = v2plugin
Cleanup = off (so it would leave everything in place.)

This job spins up 3 centos VMs, installs Docker-Swarm on them, then installs Contiv using the method as described in the documentation.  Finally, it runs a series of tests on Contiv to verify everything is working properly.

After that, I reran our terraform script for vcenter to spin up some additional VMs. 
I then manually executed the steps from the Jenkins script to prepare one of the hosts (update its software, install NTP, etc.) then install Docker-Swarm, have this node join the existing Docker-Swarm as a worker, edited the .yaml file used by Contiv's installer  to include the new node, and finally, ran the Contiv installer.

My results were similar to the ones posted.  It seems that the Contiv installer tries to install Contiv on nodes whether it needs it or not.  So the installer needs to be made smarter, or something.

I wrote up an email with more detailed directions on how to repro this.  Later I'll need to make a separate Jenkins job for testing this scenario, and similar scenarios (maybe combine it with HA, etc.?)

**Comment by rhim** [comment]
@unclejack can you please update the issue/PR with testing steps?

**Comment by rhim** [comment]
tested via e2e CI testing.

**Comment by sisudhir** [comment]
Tested the behavior with Build 1.1.3 and found that the fix is working as expected. We added a new node details in the cfg.yml without changing any other configs and were able to install Contiv on the new node added on to the existing Swarm cluster.
