### ISSUE TITLE
make[1]: *** [vagrant-clean] Error 1

### ISSUE THREAD

**Issue by subcrew** [contiv/install#339]
Hi,
I got a make error when run "make demo-legacy-swarm" as belows:
```
hbgg@node:~/install$ make demo-legacy-swarm
BUILD_VERSION=1.1.7 make cluster-legacy-swarm
make[1]: Entering directory '/users/hbgg/install'
cd cluster && vagrant destroy -f
==> kubeadm-worker0: VM not created. Moving on...
==> kubeadm-master: VM not created. Moving on...
==> swarm-mode-worker0: VM not created. Moving on...
==> swarm-mode-master: VM not created. Moving on...
==> legacy-swarm-worker0: VM not created. Moving on...
==> legacy-swarm-master: VM not created. Moving on...
Makefile:99: recipe for target 'vagrant-clean' failed
make[1]: *** [vagrant-clean] Error 1
make[1]: Leaving directory '/users/hbgg/install'
Makefile:95: recipe for target 'demo-l
```
I install vagarnt and virtualbox both from the official downloads file. OS version is Ubutnu 16.04.
```
hbgg@node:~/install$ VBoxManage -v
5.2.4r119785
hbgg@node:~/install$ vagrant --version
Vagrant 2.0.1
hbgg@node:~/install$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

```
If anybody can help me with this issue, I'll be really appreciated that.

Thanks, 
Ayakshi

**Comment by dseevr** [comment]
This is due to a bug (?) in Vagrant 2.0.1 ... `vagrant destroy -f` returns a non-zero exit code if there's nothing to do.

You can either downgrade to 2.0.0 or edit the following lines:

https://github.com/contiv/install/blob/4b5be515558a492a07e9b835c28c8a5815db30f6/Makefile#L99

and

https://github.com/contiv/install/blob/4b5be515558a492a07e9b835c28c8a5815db30f6/scripts/vbcleanup.sh#L7

and add `|| :` so they look like:

```sh
cd cluster && vagrant destroy -f || :
```

This allows execution to continue even though `vagrant` is not returning a successful exit code.

(I have no idea why the `destroy` command is duplicated... it's unnecessary :D)

**Comment by subcrew** [comment]
Thank you @dseevr , it works.
